name: Docker Base Auto Update CI

on:
  schedule:
  - cron: "23 13 3 * *"

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/armhf,linux/arm64


    steps:
    - 
      name: Docker Image Update Checker
      id: baseupdatecheck
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: library/ubuntu:latest
        image: simeononsecurity/docker-ubuntu-hardened:latest
    -
        name: Checkout
        uses: actions/checkout@v3
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.check.outputs.needs-updating == 'true'
    - 
      name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/armhf,linux/arm64 -t simeononsecurity/docker-ubuntu-hardened:latest --progress=plain --push .
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: simeononsecurity/docker-ubuntu-hardened:latest
        if: steps.check.outputs.needs-updating == 'true'
